name: Deploy Backend to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy backend to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/easy_tab_Server
          git pull origin main
          npm install
          pm2 restart file-server
          echo "Backend deployment completed successfully"
